# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 678)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #fff2e6;  /* pastel blue background */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #ff8080;\n"
"    border: 2px solid #aaa;\n"
"    border-radius: 10px;\n"
"}\n"
"QFrame#frame_2{\n"
"    background-color: #fff2e6;\n"
"    border: 2px solid #333;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame QLabel {\n"
"    background-color: #fff2e6;\n"
"    border: 2px solid #555;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid #555;\n"
"    border-radius: 8px;\n"
"    margin-top: 20px;\n"
"    padding: 10px;\n"
"    background-color: #fff2e6;\n"
"}\n"
"\n"
"/* Optional: style the title of the group box */\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 5px;\n"
"    color: #333;\n"
"    font-weight: bold; \n"
"}\n"
"\n"
"/* Style RadioButtons inside the GroupBox */\n"
"QGroupBox QRadioButton {\n"
"    border: 2px solid #aaa;\n"
"    border-radius: 4px;\n"
"    padding: 3px;\n"
"    background-color: #fff2e6;\n"
"}\n"
"\n"
"/* Style SpinBox inside the GroupBox */\n"
"QSpinBox {\n"
"    background-color: #fff2e6;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #b5e7a0;\n"
"    border: 2px solid #333;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    color: #333;\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QPushButton:hover {\n"
"    background-color: #a2d891;  /* Slightly darker green */\n"
"    border-color: #222;         /* Darker border on hover (optional) */\n"
"}\n"
"\n"
"/* Pressed effect */\n"
"QPushButton:pressed {\n"
"    background-color: #8fcf82;  /* Deeper green */\n"
"    border-color: #111;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.detButton = QtWidgets.QPushButton(self.frame)
        self.detButton.setMaximumSize(QtCore.QSize(500, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.detButton.setFont(font)
        self.detButton.setObjectName("detButton")
        self.verticalLayout.addWidget(self.detButton, 0, QtCore.Qt.AlignHCenter)
        self.stochButton = QtWidgets.QPushButton(self.frame)
        self.stochButton.setMaximumSize(QtCore.QSize(200, 300))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.stochButton.setFont(font)
        self.stochButton.setObjectName("stochButton")
        self.verticalLayout.addWidget(self.stochButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Input-Oriented Measure"))
        self.detButton.setText(_translate("MainWindow", "Deterministic"))
        self.stochButton.setText(_translate("MainWindow", "Stochastic"))
